# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uIdz30Z-zxKrgL7QEvoBghYPuMOWhSc
"""

import numpy as np #Practice on Numpy

n1 = np.array([1,2,3,4,5]) #Array
n1

n2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
n2

n3 = np.zeros((2,3)) #Zeros
n3

n4 = np.zeros((6,6)) #Zeros
n4

n5 = np.full((3,3),(5)) #Full
n5

n6 = np.full((3,8),(7)) #Full
n6

n7 = np.arange(1,50) # ARange
n7

n8 = np.arange(0,50, 5) # ARange
n8

n9 = np.random.randint(1,100,5) #Arrays with Rand
n9

n10 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #Shape
n10.shape

n10.shape = (5,2) #Shape
n10.shape
n10

